import AppKit
import ImageIO
import SwiftUI

/// Watches the pasteboard and keeps what passes through it, so the launcher can
/// paste something copied three things ago.
@MainActor
final class Clipboard {
    static let shared = Clipboard()

    private struct Item: Codable {
        /// For a picture, what to write on the row instead.
        var text: String
        var at: Date
        /// The file it was saved to, under `pictures`, when it was a picture.
        var image: String?
        /// The file that was copied, when a file was copied.
        var file: String?
        /// A small copy, made once when it was copied, under `thumbs`.
        var thumb: String?
    }

    /// Above this it is a file's worth of text rather than something to paste
    /// again, and NSUserDefaults is the wrong place to keep it. Dropped, not
    /// cut: half a payload pasted back would be worse.
    private let maxLength = 100_000
    /// A screenshot of a large display is a few megabytes; a video frame pasted
    /// by accident is not worth keeping.
    private let maxImageBytes = 12_000_000
    private let limit = 200

    /// The marker types a clipboard-aware password manager writes. A secret
    /// must never reach the history, so the watcher lets these pass unread.
    /// `pbcopy` writes none of them: `rbw get | pbcopy` is a plain string
    /// and lands here like any other, which is what `pbconceal` in dotfiles
    /// is for.
    private let ignored: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// A password manager's browser extension does not mark what it copies
    /// as concealed, but Chromium writes where a copy came from, and for an
    /// extension that is its own `chrome-extension://<id>/` page. The ids
    /// are the ones in the Chrome Web Store; a manager not listed here goes
    /// through, so this is a floor and not a guarantee.
    private static let sourceType = NSPasteboard.PasteboardType("org.chromium.source-url")
    private static let managers: Set<String> = [
        "nngceckbapebfimnlniiiahkandclblb", // Bitwarden
        "aeblfdkhhhdcdjpifhhbdiojplfjncoa", // 1Password
        "hdokiejnpimakedhajhdlcegeplioahd", // LastPass
        "fdjamakpfbbddfjaooikfcpapjohcfmg", // Dashlane
        "bfogiafebfohielmmehodmfbbebbbpei", // Keeper
        "ghmbeldphafepmbegfdlkpapadhbakde", // Proton Pass
        "hlaiofkbmjenhgeinjlmkafaipackfjh", // Proton Pass (beta)
    ]

    private static func fromManager(_ board: NSPasteboard) -> Bool {
        guard let source = board.string(forType: sourceType),
              let url = URL(string: source), url.scheme == "chrome-extension",
              let host = url.host
        else { return false }

        return managers.contains(host)
    }

    private let cache = FileManager.default
        .homeDirectoryForCurrentUser
        .appendingPathComponent(".cache/sottomano")

    private var url: URL { cache.appendingPathComponent("clipboard.enc") }
    /// Where the history was kept in the clear, read once more and removed
    /// on the first save after it.
    private var legacy: URL { cache.appendingPathComponent("clipboard.json") }
    private var pictures: URL { cache.appendingPathComponent("clipboard") }
    private var thumbs: URL { cache.appendingPathComponent("thumbs") }

    /// Loaded once per run: opening the panel should not read the same two
    /// hundred small files again.
    private var loaded: [String: NSImage] = [:]

    private var items: [Item]
    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?
    /// Set while something borrows the pasteboard rather than writing to it.
    private var paused = false

    private init() {
        let sealed = (try? Data(contentsOf: cache.appendingPathComponent("clipboard.enc"))).flatMap(Sealed.open)
        let data = sealed ?? (try? Data(contentsOf: cache.appendingPathComponent("clipboard.json"))) ?? Data()

        items = (try? JSONDecoder().decode([Item].self, from: data)) ?? []
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { _ in
            Task { @MainActor in Clipboard.shared.poll() }
        }
    }

    func pause() {
        paused = true
    }

    func resume() {
        lastChange = NSPasteboard.general.changeCount
        paused = false
    }

    func choices() -> [Choice] {
        items.enumerated().map { index, item in
            let picture = item.image.map { pictures.appendingPathComponent($0).path }
            // a copied file is worth seeing when it is a picture, and worth
            // wearing its own icon when it is anything else
            let showable = item.file.flatMap { NSImage(contentsOfFile: $0) != nil ? $0 : nil }
            // a number that is a moment is told apart here, once per row: the
            // row says when it is, and selecting it lays out every form of it
            let kind = item.image == nil && item.file == nil ? Clipboard.read(item.text) : nil
            return Choice(
                value: item.text,
                name: item.file.map { ($0 as NSString).lastPathComponent } ?? item.text
                    .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
                    .trimmingCharacters(in: .whitespacesAndNewlines),
                subtitle: Clipboard.ago(item.at) + " · " + (kind?.summary ?? Clipboard.size(item)),
                // With no query every score is 0, so the order is the order they
                // are in — the newest first. No boost at all: an integer
                // division into ten steps put whole handfuls of rows on the
                // same rung and left the tie to be broken by something else.
                boost: 0,
                icon: icon(for: item),
                color: Clipboard.colour(of: item.text),
                imageFile: picture ?? showable,
                details: kind?.details,
                tree: kind?.tree,
                fileURL: item.file,
                symbol: kind?.symbol ?? Clipboard.symbol(for: item)
            )
        }
    }

    /// What a row of text is, when it is data rather than words: what the
    /// row says beside it, the icon it wears, and what goes beside the list.
    struct Kind {
        var summary: String
        var symbol: String
        var details: [Detail]?
        var tree: JSONValue?
    }

    /// Told once per row, in the order of how sure each test is: a timestamp
    /// and a document are unmistakable, a token nearly so, hex needs a
    /// length, and base64 is anything long enough in the right alphabet, so
    /// it goes last.
    private static func read(_ text: String) -> Kind? {
        if let stamp = Timestamp(text) {
            return Kind(summary: stamp.utc, symbol: "clock", details: stamp.details)
        }

        if let first = text.first(where: { !$0.isWhitespace }), first == "{" || first == "[",
           let document = JSONValue.parse(text) {
            let summary = switch document {
            case .object(let pairs): "Object · \(pairs.count) \(pairs.count == 1 ? "key" : "keys")"
            case .array(let items): "Array · \(items.count) \(items.count == 1 ? "item" : "items")"
            default: ""
            }

            return Kind(summary: summary, symbol: "curlybraces", tree: document)
        }

        if let token = JWT(text) {
            return Kind(summary: token.summary, symbol: "key", tree: token.document)
        }

        // the sized ones before the bare run of hex, which would take them
        if let evm = EVM(text) {
            return Kind(summary: evm.summary, symbol: "hexagon", details: evm.details)
        }

        if let id = ObjectId(text) {
            return Kind(summary: id.summary, symbol: "leaf", details: id.details)
        }

        if let uuid = UUIDReader(text) {
            return Kind(summary: uuid.summary, symbol: "number", details: uuid.details)
        }

        if let cron = Cron(text) {
            return Kind(summary: cron.summary, symbol: "calendar", details: cron.details)
        }

        if let hex = Hex(text) {
            return Kind(summary: "Hex · " + hex.summary, symbol: "number", details: hex.details)
        }

        if let decoded = Base64.text(of: text) {
            // what was encoded is often a document, and then it is one
            if let first = decoded.first(where: { !$0.isWhitespace }), first == "{" || first == "[",
               let document = JSONValue.parse(decoded) {
                return Kind(summary: "Base64 · JSON", symbol: "arrow.left.arrow.right", tree: document)
            }

            return Kind(
                summary: "Base64 · \(decoded.count) chars",
                symbol: "arrow.left.arrow.right",
                details: [Detail("Decoded", decoded)]
            )
        }

        return nil
    }

    /// What a row of text looks like at a glance: an address, a colour, several
    /// lines, or a few words.
    private static func symbol(for item: Item) -> String? {
        guard item.image == nil, item.file == nil else { return nil }

        let trimmed = item.text.trimmingCharacters(in: .whitespacesAndNewlines)

        if colour(of: trimmed) != nil { return nil }
        if trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://") { return "link" }
        if trimmed.contains("\n") { return "text.alignleft" }

        return "textformat"
    }

    /// The small copy made when it was copied, kept in memory after the first
    /// read. Anything without one wears the icon of its kind, which costs
    /// nothing — decoding two hundred photographs on every open is what made
    /// the panel take a moment to appear.
    private func icon(for item: Item) -> NSImage? {
        if let thumb = item.thumb {
            let path = thumbs.appendingPathComponent(thumb).path

            if let ready = loaded[path] { return ready }

            if let image = NSImage(contentsOfFile: path) {
                loaded[path] = image

                return image
            }
        }

        return item.file.map { NSWorkspace.shared.icon(forFile: $0) }
    }

    /// Makes the small copy, once. Returns the name it was saved under.
    private func makeThumb(of path: String) -> String? {
        guard let image = Clipboard.thumbnail(path, size: 64),
              let data = Clipboard.png(image)
        else { return nil }

        let name = "\(abs(path.hashValue))-\(Int(Date().timeIntervalSince1970)).png"

        try? FileManager.default.createDirectory(at: thumbs, withIntermediateDirectories: true)
        try? data.write(to: thumbs.appendingPathComponent(name))

        return name
    }

    /// A small copy, decoded small. Reading a 24-megapixel photograph to draw it
    /// at 22 points would decode the whole thing first, once per row.
    static func thumbnail(_ path: String, size: Int) -> NSImage? {
        guard let source = CGImageSourceCreateWithURL(URL(fileURLWithPath: path) as CFURL, nil)
        else { return nil }

        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: size,
        ]

        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary)
        else { return nil }

        return NSImage(cgImage: image, size: NSSize(width: image.width, height: image.height))
    }

    /// Hands the file back to whoever is pasting, so it lands as a file rather
    /// than as the text of its path.
    func put(file: String) {
        pause()

        NSPasteboard.general.clearContents()
        NSPasteboard.general.writeObjects([URL(fileURLWithPath: file) as NSURL])

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) { [weak self] in
            self?.resume()
        }
    }

    /// Puts a picture back where it came from. Text is typed instead, which
    /// leaves the pasteboard alone, but a picture cannot be typed.
    func put(_ file: String) {
        guard let image = NSImage(contentsOfFile: file) else { return }

        pause()

        NSPasteboard.general.clearContents()
        NSPasteboard.general.writeObjects([image])

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) { [weak self] in
            self?.resume()
        }
    }

    /// Moves what was just pasted back to the top. The date goes with it: the
    /// entry has been through the pasteboard again, and leaving it behind would
    /// put a row that reads "3h ago" above one that reads "now".
    func promote(_ choice: Choice) {
        guard let found = index(of: choice), found != 0 else { return }

        var item = items.remove(at: found)
        item.at = Date()

        items.insert(item, at: 0)
        save()
    }

    /// Takes a row out, with its picture: for the password that went through
    /// pbcopy and should not be kept, or anything else that should not be.
    func remove(_ choice: Choice) {
        guard let found = index(of: choice) else { return }

        let dropped = items.remove(at: found)

        if let image = dropped.image {
            try? FileManager.default.removeItem(at: pictures.appendingPathComponent(image))
        }

        if let thumb = dropped.thumb {
            try? FileManager.default.removeItem(at: thumbs.appendingPathComponent(thumb))
        }

        save()
    }

    private func index(of choice: Choice) -> Int? {
        items.firstIndex { item in
            if let image = item.image {
                return pictures.appendingPathComponent(image).path == choice.imageFile
            }

            if let file = item.file { return file == choice.fileURL }

            return item.text == choice.value
        }
    }

    private func poll() {
        let board = NSPasteboard.general

        guard !paused, board.changeCount != lastChange else { return }

        lastChange = board.changeCount

        let types = Set((board.types ?? []).map(\.rawValue))

        guard types.isDisjoint(with: ignored), !Clipboard.fromManager(board) else { return }

        // A file copied in the Finder arrives as a URL *and* as its path in
        // text, so the URL has to be looked at first or every file would be
        // remembered as a string that happens to look like a path.
        if let urls = board.readObjects(forClasses: [NSURL.self]) as? [URL],
           let file = urls.first(where: \.isFileURL) {
            record(Item(text: file.path, at: Date(), file: file.path, thumb: makeThumb(of: file.path)))

            return
        }

        if let text = board.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard text.count <= maxLength else { return }

            record(Item(text: text, at: Date()))

            return
        }

        // a screenshot arrives as pixels and nothing else, and it is the thing
        // most often on the pasteboard that is not words
        guard let data = board.data(forType: .png) ?? board.data(forType: .tiff),
              data.count <= maxImageBytes,
              let image = NSImage(data: data)
        else { return }

        let name = "\(Int(Date().timeIntervalSince1970 * 1000)).png"

        try? FileManager.default.createDirectory(at: pictures, withIntermediateDirectories: true)
        try? Clipboard.png(image)?.write(to: pictures.appendingPathComponent(name))

        let size = image.size

        let saved = pictures.appendingPathComponent(name).path

        record(
            Item(
                text: "image \(Int(size.width))×\(Int(size.height))",
                at: Date(),
                image: name,
                thumb: makeThumb(of: saved)
            )
        )
    }

    private func record(_ item: Item) {
        // Every copy is a row of its own. Folding a repeat into the entry that
        // was already there made the old one vanish from where it stood, which
        // reads as the list losing something rather than gaining it.
        items.insert(item, at: 0)

        // the pictures of what fell off the end go with it
        for dropped in items.dropFirst(limit) {
            if let image = dropped.image {
                try? FileManager.default.removeItem(at: pictures.appendingPathComponent(image))
            }

            if let thumb = dropped.thumb {
                try? FileManager.default.removeItem(at: thumbs.appendingPathComponent(thumb))
            }
        }

        items = Array(items.prefix(limit))

        save()
    }

    private func save() {
        try? FileManager.default.createDirectory(at: cache, withIntermediateDirectories: true)

        guard let data = try? JSONEncoder().encode(items), let sealed = Sealed.seal(data) else { return }

        // written whole and swapped in: a crash halfway through a write would
        // otherwise leave a file that no longer opens
        try? sealed.write(to: url, options: .atomic)
        try? FileManager.default.removeItem(at: legacy)
    }

    private static func png(_ image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiff)
        else { return nil }

        return bitmap.representation(using: .png, properties: [:])
    }

    /// Text that names a colour is more use seen than read.
    private static func colour(of text: String) -> Color? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)

        if trimmed.hasPrefix("#"), trimmed.count == 4 || trimmed.count == 7 || trimmed.count == 9,
           trimmed.dropFirst().allSatisfy(\.isHexDigit) {
            return Color(hex: trimmed)
        }

        let numbers = trimmed
            .replacingOccurrences(of: "rgba?\\(|\\)", with: "", options: .regularExpression)
            .split(whereSeparator: { ", ".contains($0) })
            .compactMap { Double($0) }

        guard trimmed.lowercased().hasPrefix("rgb"), numbers.count >= 3 else { return nil }

        return Color(
            .sRGB,
            red: numbers[0] / 255,
            green: numbers[1] / 255,
            blue: numbers[2] / 255,
            opacity: numbers.count > 3 ? numbers[3] : 1
        )
    }

    private static func ago(_ date: Date) -> String {
        let delta = Int(Date().timeIntervalSince(date))

        if delta < 60 { return "now" }
        if delta < 3600 { return "\(delta / 60)m ago" }
        if delta < 86400 { return "\(delta / 3600)h ago" }

        return "\(delta / 86400)d ago"
    }

    private static func size(_ item: Item) -> String {
        if item.image != nil { return "picture" }

        if let file = item.file {
            let folder = (file as NSString).deletingLastPathComponent
            let home = FileManager.default.homeDirectoryForCurrentUser.path

            return folder.hasPrefix(home) ? "~" + folder.dropFirst(home.count) : folder
        }


        let lines = item.text.components(separatedBy: "\n").count

        return lines > 1 ? "\(lines) lines" : "\(item.text.count) chars"
    }
}
