import AppKit

/// Watches the pasteboard and keeps what passes through it, so the launcher can
/// paste something copied three things ago.
@MainActor
final class Clipboard {
    static let shared = Clipboard()

    private struct Item: Codable {
        var text: String
        var at: Date
    }

    /// Above this it is a file's worth of text rather than something to paste
    /// again. Dropped, not cut: half a payload pasted back is worse.
    private let maxLength = 100_000
    private let limit = 200

    /// The marker types every password manager writes, rbw included. A secret
    /// must never reach the history, so these pasteboards are left unread.
    private let ignored: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private let url = FileManager.default
        .homeDirectoryForCurrentUser
        .appendingPathComponent(".cache/sottomano/clipboard.json")

    private var items: [Item]
    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?
    /// Set while something borrows the pasteboard rather than writing to it.
    private var paused = false

    private init() {
        let data = (try? Data(contentsOf: url)) ?? Data()
        items = (try? JSONDecoder().decode([Item].self, from: data)) ?? []
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { _ in
            Task { @MainActor in Clipboard.shared.poll() }
        }
    }

    func pause() {
        paused = true
    }

    func resume() {
        lastChange = NSPasteboard.general.changeCount
        paused = false
    }

    func choices() -> [Choice] {
        items.enumerated().map { index, item in
            Choice(
                value: item.text,
                name: item.text.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
                    .trimmingCharacters(in: .whitespacesAndNewlines),
                subtitle: Clipboard.ago(item.at) + " · " + Clipboard.size(item.text),
                // with no query every score is 0, so this alone orders by
                // recency. Small, so that typing puts the match back in charge.
                boost: (items.count - index) * 10 / max(items.count, 1)
            )
        }
    }

    private func poll() {
        let board = NSPasteboard.general

        guard !paused, board.changeCount != lastChange else { return }

        lastChange = board.changeCount

        let types = Set((board.types ?? []).map(\.rawValue))

        guard types.isDisjoint(with: ignored) else { return }
        guard let text = board.string(forType: .string), !text.isEmpty else { return }
        guard text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false else { return }
        guard text.count <= maxLength else { return }

        // copied again, an entry moves back to the top rather than appearing twice
        items.removeAll { $0.text == text }
        items.insert(Item(text: text, at: Date()), at: 0)
        items = Array(items.prefix(limit))

        try? FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        try? JSONEncoder().encode(items).write(to: url)
    }

    private static func ago(_ date: Date) -> String {
        let delta = Int(Date().timeIntervalSince(date))

        if delta < 60 { return "now" }
        if delta < 3600 { return "\(delta / 60)m ago" }
        if delta < 86400 { return "\(delta / 3600)h ago" }

        return "\(delta / 86400)d ago"
    }

    private static func size(_ text: String) -> String {
        let lines = text.components(separatedBy: "\n").count

        return lines > 1 ? "\(lines) lines" : "\(text.count) chars"
    }
}
